applications/provenance/system_settings/account_management/urls.py
from django.urls import path

from account_management.views.login_screen import login

app_name = "account_management"

urlpatterns = [
    path('login/', login, name='HomeScreenLogin'),
]

docs/utils/urls_communal/urls.py
from django.urls import re_path

from docs.utils.views import VueHome

ADD_TOOL_URL = [
    # http://0.0.0.0:8000/Chunnel/Tool
    re_path(r'$', VueHome.as_view()),
    # # http://0.0.0.0:8000/Chunnel/Tool/LeftSidebar/2aPaPHbvhpgibCmV9VF2szUKUD4oBNVE
    # re_path(r'^LeftSidebar/(?P<sidebar>\w{32})$', LeftSidebar.as_view()),
    # # http://0.0.0.0:8000/Chunnel/Tool/LeftSidebarSon/2aPaPHbvhpgibCmV9VF2szUKUD4oBNVE
    # re_path(r'^LeftSidebarSon/(?P<sidebar>\w{32})$', LeftSidebarSon.as_view()),
    # # http://0.0.0.0:8000/Chunnel/Tool/LeftSidebarSonContent/e4c3267869244e90b4a54361a8b9c045
    # re_path(r'^LeftSidebarSonContent/(?P<sidebar>\w{32})$', LeftSidebarSonContent.as_view()),
]

entirely/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.views import serve
from django.urls import path, include, re_path

# 站点标题
admin.site.site_title = '小李的窝'  # 网站标签页名称
admin.site.site_header = '李思源的老窝'  # 网站名称：显示在登录页和首页

urlpatterns = [
    path('sp/', include('simplepro.urls')),
    path(settings.ADMIN_URL_ZDY, admin.site.urls),
    path('Menu/', include('menu_management.urls', namespace='menu_management')),
    path('Account/', include('account_management.urls', namespace='account_management')),
    # re_path(r'^docs/static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    # re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings_entirely.MEDIA_ROOT}),
    # path('favicon.ico', RedirectView.as_view(url=r'docs/static/images/favicon.svg')),
    # path('favicon', RedirectView.as_view(url=r'docs/static/images/favicon.svg')),
    # path('null_svg', RedirectView.as_view(url=r'docs/static/images/null.svg')),
    # path('admin_png', RedirectView.as_view(url=r'docs/static/images/19990929.jpg')),
    # re_path(r'$', DjangoHome.as_view()),
]
if settings.DEBUG:
    # urlpatterns += static(settings_entirely.MEDIA_URL, document_root=settings_entirely.MEDIA_ROOT)
    # urlpatterns += staticfiles_urlpatterns()  # from django.contrib.staticfiles.urls import staticfiles_urlpatterns
    urlpatterns += static(settings.STATIC_URL, view=serve)
else:
    # urlpatterns += static(settings_entirely.MEDIA_URL, document_root=settings_entirely.MEDIA_ROOT) + static(
    #     settings_entirely.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL)
# handler400 = bad_request
# handler403 = permission_denied
# handler404 = page_not_found
# handler500 = server_error

docs/utils/views_communal/views.py
# import json
# import random
#
# from django.http import JsonResponse, HttpResponse
# from django.shortcuts import render, get_object_or_404
# from django.views import View
# from django.views.decorators.http import require_http_methods
#

# from Blog.models import BlogWritings
# from li.settings import DATABASES_MYSQL, DATABASES_MYSQL_CONN, DATABASES_MYSQL_CURSOR


# from simplepro.monitor.views import JsonResponse
# from django.shortcuts import render, get_object_or_404

# Create your views here.


# def get_post(request):
#     if request.method.upper() == "GET":
#         return JsonResponse(data={'GET': request.method.upper()})
#     elif request.method.upper() == "POST":
#         return JsonResponse(data={'POST': request.method.upper()})
#     else:
#         return JsonResponse(data={})


# class Home(View):
#     def post(self, request):
#         data_home = {}
#         for i in range(10):
#             key_id = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))
#             data_home['{}'.format(key_id)] = {}
#             data_home[key_id].update({
#                 "key_id": key_id,
#                 "name": 'name{}'.format(i),
#                 "svg_path": "/docs/media/images/02GOB7JF.png",
#             })
#         return JsonResponse(data=data_home)
#         # return HttpResponse(json.dumps(data_home), content_type="application/json")  # 第二种

# class VueHome(View):
#     def get(self, request):
#         data_home = {}
#         for i in range(10):
#             key_id = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))
#             data_home['{}'.format(key_id)] = {}
#             data_home[key_id].update({
#                 "key_id": key_id,
#                 "name": 'name{}'.format(i),
#                 "svg_path": "/docs/media/images/02GOB7JF.png",
#             })
#         return JsonResponse(data=data_home)
#         # return HttpResponse(json.dumps(data_home), content_type="application/json")  # 第二种


# class LeftSidebar(View):
#     def get(self, request, sidebar=None):
#         data_home = {sidebar: {}}
#         for i in range(10):
#             key_id = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))
#             data_home[sidebar]['{}'.format(key_id)] = {}
#             data_home[sidebar][key_id].update({
#                 "key_id": key_id,
#                 "name": 'name{}'.format(i),
#                 "svg_path": "/docs/media/images/02GOB7JF.svg",
#             })
#         return JsonResponse(data=data_home)
#
#
# class LeftSidebarSon(View):
#     def get(self, request, sidebar=None):
#         data_home = {sidebar: {}}
#         for i in range(10):
#             key_id = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=32))
#             data_home[sidebar]['{}'.format(key_id)] = {}
#             data_home[sidebar][key_id].update({
#                 # "key_id": "e4c3267869244e90b4a54361a8b9c045",
#                 "key_id": key_id,
#                 "name": 'name{}'.format(i),
#                 "svg_path": "/docs/media/images/02GOB7JF.svg",
#             })
#         return JsonResponse(data=data_home)
#
#
# class LeftSidebarSonContent(View):
#     def get(self, request, sidebar=None):
#         try:
#             content = get_object_or_404(BlogWritings, ID=sidebar)
#             data_home = {sidebar: {
#                 "key_id": sidebar,
#                 "content": content.BLOG_CONTENT
#             }}
#             click_number = content.BLOG_CLINK + 1
#             BlogWritings.objects.filter(ID=sidebar).update(BLOG_CLINK=click_number)
#             return JsonResponse(data=data_home)
#         except Exception as e:
#             content = ''.join(random.choices('ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789', k=10))
#             return JsonResponse(data={sidebar: {"key_id": sidebar, "content": '密钥：{}'.format(content)}})

docs/templates/cornerstone 3.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{{ site_title|default:_('entirely') }}{% endblock %}</title>
    <title>entirely</title>
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/csrf.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap-5.3.0/css/bootstrap.min.css' %}">
    <script src="{% static 'plugins/bootstrap/bootstrap-5.3.0/js/bootstrap.bundle.min.js' %}"></script>
    {% block css %}{% endblock %}
    {% block script %}{% endblock %}
</head>
<body>
<div class="mw-100" style="width: 100%; height: 100%;">
    <div class="container sticky-top">
        <div class="mh-100" style="width: 100%; height: 5%;">
            <div class="">
                <div class="alert alert-light font-weight-bolder text-center" role="alert">
                    {% if error_data %}
                        {{ error_data }}
                    {% else %}
                        欢迎
                    {% endif %}
                </div>
                <div class="alert alert-light font-weight-bolder text-center" role="alert">
                    {% if request.user.is_authenticater%}
                        注销
                    {% else %}
                        <a href="{% url 'account_management:HomeScreenLogin' %}">登陆</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% block body_top %}{% endblock %}
    </div>
    <div class="row">
        {% block body_middle %}
            <div class="col-sm-1">
                {% block body_left %}{% endblock %}
            </div>
            <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                    <symbol id="info-fill" viewBox="0 0 16 16">
                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                    </symbol>
                </svg>
                {% for nume_title in data.data %}
                    <div class="alert alert-primary d-flex align-items-center" role="alert">
                        {#                        <svg href="{% static 'images/currency/查找学习.svg' %}">#}
                        {#                            <use xlink:href="#info-fill"/>#}
                        {#                        </svg>#}
                        {#                            <img src="{% static 'images/currency/查找学习.svg' %}" class="img-thumbnail" alt="...">#}
                        {#                        <div>#}
                        <span class="badge rounded-pill text-bg-light">{{ nume_title.id }}.{{ nume_title.NAME }}</span>
                        {#                        </div>#}
                        {#                        <img src="{% static 'images/currency/查找学习.svg' %}" class="img-thumbnail" alt="...">#}
                    </div>
                {% endfor %}
            </div>
            <div class="col-sm-1">
                {% block body_right %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
    <div class="sticky-bottom">
        <div class="container">
            {% block body_down %}{% endblock %}
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <p class="col-md-4 mb-0 text-muted">© 2023 li</p>
            </footer>
        </div>
    </div>
</div>
</body>
</html>

docs/templates/cornerstone.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{{ title }}{{ site_title|default:_('entirely') }}{% endblock %}</title>
    <title>entirely</title>
    <script src="{% static 'js/jquery-3.7.0.min.js' %}"></script>
    <script src="{% static 'js/csrf.js' %}"></script>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap/bootstrap-5.3.0/css/bootstrap.min.css' %}">
    <script src="{% static 'plugins/bootstrap/bootstrap-5.3.0/js/bootstrap.bundle.min.js' %}"></script>
    {% block css %}{% endblock %}
    {% block script %}{% endblock %}
</head>
<body>
<div class="mw-100" style="width: 100%; height: 100%;">
    <div class="container sticky-top">
        <div class="mh-100" style="width: 100%; height: 5%;">
            <div class="">
                <div class="alert alert-light font-weight-bolder text-center" role="alert">
                    {% if error_data %}
                        {{ error_data }}
                    {% else %}
                        欢迎
                    {% endif %}
                </div>
                <div class="alert alert-light font-weight-bolder text-center" role="alert">
                    {% if request.user.is_authenticater%}
                        注销
                    {% else %}
                        <a href="{% url 'account_management:HomeScreenLogin' %}">登陆</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% block body_top %}{% endblock %}
    </div>
    <div class="row">
        {% block body_middle %}
            <div class="col-sm-1">
                {% block body_left %}{% endblock %}
            </div>
            <div class="col">
                <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                    <symbol id="info-fill" viewBox="0 0 16 16">
                        <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
                    </symbol>
                </svg>
                {% for nume_title in data.data %}
                    <div class="alert alert-primary d-flex align-items-center" role="alert">
                        {#                        <svg href="{% static 'images/currency/查找学习.svg' %}">#}
                        {#                            <use xlink:href="#info-fill"/>#}
                        {#                        </svg>#}
                        {#                            <img src="{% static 'images/currency/查找学习.svg' %}" class="img-thumbnail" alt="...">#}
                        {#                        <div>#}
                        <span class="badge rounded-pill text-bg-light">{{ nume_title.id }}.{{ nume_title.NAME }}</span>
                        {#                        </div>#}
                        {#                        <img src="{% static 'images/currency/查找学习.svg' %}" class="img-thumbnail" alt="...">#}
                    </div>
                {% endfor %}
            </div>
            <div class="col-sm-1">
                {% block body_right %}
                {% endblock %}
            </div>
        {% endblock %}
    </div>
    <div class="sticky-bottom">
        <div class="container">
            {% block body_down %}{% endblock %}
            <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <p class="col-md-4 mb-0 text-muted">© 2023 li</p>
            </footer>
        </div>
    </div>
</div>
</body>
</html>